version: "3"
services:
  nginx:
    image: nginx
    container_name: step1-nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ../app/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80